# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  workflow_dispatch:

jobs:
  start:

    runs-on: macos-latest

    steps:
    - name: Install python
      run: |
        xcode-select --install
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew install python3
      
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
    - name: Build and publish
      env:
        DISCORD_BOT: ${{ secrets.DISCORD_BOT }}
      run: |
        python3 bot.py
